# Generated by Django 4.2.1 on 2023-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_task_completed_ctask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='ctask',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
