# Generated by Django 4.2.1 on 2023-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_completed_ctask_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateTimeField(null=True),
        ),
    ]
